apiVersion: v1
kind: Service                     # Создаем сервис
metadata:
  name: k8s-demo-node-port           # Название сервиса
spec:
  type: NodePort                  # Указываем тип
  selector:
    app: k8s-demo-pod # Указываем селектор пода
  ports:                          # Указываем порты
    - port: 80                  # Порт пода
      targetPort: 80            # По умолчанию совподает со значением port
      # Опциональное поле. Значение должно находится в диапазоне 30000-32767
      nodePort: 31313             # Указываем раскрываемый этим сервисом номер порта
